# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tcIWsWLltq8mBCi2Uh90E3RsOkEdw2lQ
"""

# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7-xjibvUvnTWviQP674X9EMFhevNUN
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5, 6, 7])
y = np.array([0, 0, 1, -0.5, 0, 0, 0, 0])

plt.plot(x, y, color='red', marker='o')
plt.title("Tiriklik ko'rsatkichlari")
plt.xlabel("Vaqt")
plt.ylabel("Amplitude")
plt.grid(True)

plt.show()

import matplotlib.pyplot as plt
import numpy as np
y = np.array([3,8,1,10])
plt.plot(y, marker= 'o', ms= 20,
mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1 = np.array([0,1,2,3])
y1 = np.array([3,8,1,10])
x2 = np.array([0,1,2,3])
y2 = np.array([6,2,7,11])
plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([0,1,2,3,4,5])
y = np.array([0,8,12,20,26,38])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([0,1,2,3,4,5])
y = np.array([0,2,8,1,14,7])
plt.scatter(x,y,color='red')
x = np.array([12,6,8,11,8,3])
y = np.array([5,6,3,7,17,19])
plt.scatter(x,y,color='green')
plt.show()